seed: 42

# audio48 / 2ch input / original FM loss

# WANDB
wandb:
  project_name: "Flow Matching"
  entity: "woongzip1"
  run_name: "run0"
  notes: "First training"

# DATALOADER
dataloader:
  batch_size: 8
  num_workers: 4
  prefetch_factor: 2
  persistent_workers: True
  pin_memory: True

# DATASET
dataset:
  ratio: 1
  common:
    num_samples: 32767
    sr: 48000
    sr_lr: 8000
  train:
    tsv_path: "./data/speech_48.txt"
  val:
    tsv_path: "./data/speech_48_val.txt"
  test:
    tsv_path: "./data/libri-test.txt"

# Path
path:
  class_path: src.flow.path_stft.OriginalCFMPath
  init_args:
    {}

# Transform
transform:
  window_fn: 'hann'
  n_fft: 1024 
  sampling_rate: 48000 
  hop_length: 512
  alpha: 0.3 
  beta: 1 
  comp_eps: 1.0e-4

model:
  in_channels: 4 
  out_channels: 2 
  dims: [96, 192, 384, 768] # [64, 128, 256, 512]
  depths: [2,2,4,2]
  
optimizer:
  learning_rate: 1.0e-4

train:
  num_epochs: 200
  ckpt_save_dir: ./ckpts_cfm_speech/
  ckpt_load_path: "./ckpts_cfm_speech/cfm_20.pth"
  # ckpt_load_path: null
  # eta: 0.5

inference:
  dir_speech: "./inference/audio"